import { useEffect, useMemo, useState } from 'react';
import {
  BarChart2, Check, ChevronDown, ChevronUp, Download, Eye, FileSpreadsheet,
  FileText, LayoutDashboard, Palette, Plus, Save, Search, Settings2, Star,
  Trash2, X
} from 'lucide-react';
import { getReports, deleteReport, toggleStar } from '../lib/db.js';
import { useAuth } from '../hooks/useAuth.jsx';
import { useToast } from '../hooks/useToast.jsx';
import { exportReportPDF } from '../utils/pdfExport.js';
import { exportBomPDF, exportBomExcel } from '../utils/bomExport.js';
import { PageHeader } from '../components/ResultCard.jsx';

const REPORT_TEMPLATE_KEY = 'textileie_report_templates_v1';
const REPORT_SETTINGS_KEY = 'textileie_report_settings_v1';

const TYPE_LABEL = {
  efficiency: 'Efficiency', capacity: 'Capacity', smv: 'SMV / SAM', fabric: 'Fabric BOM',
  thread: 'Thread Engineering', costing: 'Garment Costing', yarn: 'Yarn'
};
const TYPE_BADGE = {
  efficiency: 'teal', capacity: 'navy', smv: 'amber', fabric: 'green',
  thread: 'purple', costing: 'orange', yarn: 'red'
};

const TABS = [
  { id: 'standard', label: 'Standard Reports', icon: FileText },
  { id: 'builder', label: 'Custom Builder', icon: Palette },
  { id: 'templates', label: 'Saved Templates', icon: Star },
  { id: 'executive', label: 'Executive Reports', icon: LayoutDashboard },
];

const DEFAULT_REPORT_SETTINGS = {
  companyLogo: '', companyAddress: '', defaultPaper: 'A4', defaultOrientation: 'portrait',
  footer: 'Generated by TextileIE', watermark: '', preparedBy: '', checkedBy: '', approvedBy: '',
  showPageNumber: true, showGeneratedBy: true,
};

function loadJson(key, fallback) {
  try { return JSON.parse(localStorage.getItem(key) || '') || fallback; }
  catch { return fallback; }
}
function saveJson(key, value) { localStorage.setItem(key, JSON.stringify(value)); }
function titleCase(value) {
  return String(value || '').replace(/_/g, ' ').replace(/([a-z])([A-Z])/g, '$1 $2').replace(/^./, s => s.toUpperCase());
}
function safeValue(value) {
  if (value === null || value === undefined || value === '') return '—';
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value);
}
function hasBomData(report) {
  try {
    const parsed = JSON.parse(report?.inputs?._bomData || '');
    return Boolean(parsed?.components?.length && parsed?.sizes?.length);
  } catch { return false; }
}
function getBomData(report) {
  try { return JSON.parse(report?.inputs?._bomData || ''); }
  catch { return null; }
}
function getArticle(report) {
  return report?.inputs?.articleNumber || report?.inputs?.article_number || report?.inputs?.artNo || '';
}
function getKeyResult(report) {
  const r = report?.results || {};
  if (report.type === 'efficiency') return `${Number(r.efficiency || 0).toFixed(2)}%`;
  if (report.type === 'capacity') return `${Number(r.dailyCapacity || 0).toLocaleString()} pcs/day`;
  if (report.type === 'smv') return `${Number(r.totalSMV || r.combinedSMV || 0).toFixed(3)} min`;
  if (report.type === 'costing') return `${Number(r.fobPrice || 0).toFixed(2)} FOB`;
  if (report.type === 'thread') return `${Number(r.totalMeters || r.grossMeters || 0).toFixed(2)} m`;
  if (report.type === 'fabric') return r['L total'] || r.totalFabricCost || 'BOM';
  return 'Saved';
}
function createFieldRows(report) {
  const hidden = new Set(['_bomData']);
  const rows = [];
  Object.entries(report?.inputs || {}).forEach(([key, value]) => {
    if (!hidden.has(key) && typeof value !== 'object') rows.push({ id: `input:${key}`, source: 'inputs', key, label: titleCase(key), value: safeValue(value), visible: true });
  });
  Object.entries(report?.results || {}).forEach(([key, value]) => {
    if (typeof value !== 'object') rows.push({ id: `result:${key}`, source: 'results', key, label: titleCase(key), value: safeValue(value), visible: true });
  });
  return rows;
}
function escapeHtml(value) {
  return String(value ?? '').replace(/[&<>'"]/g, ch => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[ch]));
}
function downloadExcel({ title, fields, settings }) {
  const rows = fields.filter(f => f.visible).map((f, i) => `<tr style="background:${i % 2 ? '#fff' : '#F4F7FA'}"><td style="border:1px solid #D8E4EE;padding:7px">${escapeHtml(f.label)}</td><td style="border:1px solid #D8E4EE;padding:7px;font-weight:bold;color:#0D7A6B">${escapeHtml(f.value)}</td></tr>`).join('');
  const html = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel"><head><meta charset="UTF-8"></head><body><table><tr><td colspan="2" style="background:#0F2942;color:white;font-size:15pt;font-weight:bold;padding:10px">${escapeHtml(title)}</td></tr><tr><td colspan="2" style="background:#E4F4F1;padding:7px">${escapeHtml(settings.companyAddress || '')}</td></tr><tr><th style="background:#0D7A6B;color:white;padding:7px">Field</th><th style="background:#0D7A6B;color:white;padding:7px">Value</th></tr>${rows}<tr><td colspan="2" style="color:#64748b;padding:8px">${escapeHtml(settings.footer || '')}</td></tr></table></body></html>`;
  const blob = new Blob([html], { type: 'application/vnd.ms-excel;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a'); a.href = url; a.download = `${title.replace(/[^a-z0-9]+/gi, '-')}-${Date.now()}.xls`;
  document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url);
}
function printCustomReport({ title, fields, settings, profile }) {
  const rows = fields.filter(f => f.visible).map(f => `<tr><td>${escapeHtml(f.label)}</td><td>${escapeHtml(f.value)}</td></tr>`).join('');
  const win = window.open('', '_blank');
  if (!win) return;
  win.document.write(`<!doctype html><html><head><meta charset="UTF-8"><title>${escapeHtml(title)}</title><style>@page{size:${settings.defaultPaper} ${settings.defaultOrientation};margin:18mm}body{font-family:Arial;color:#0F2942}header{border-bottom:3px solid #0D7A6B;padding-bottom:12px;margin-bottom:18px}.brand{font-size:22px;font-weight:700}.meta{font-size:11px;color:#64748b;margin-top:5px}table{width:100%;border-collapse:collapse}td{padding:8px;border:1px solid #D8E4EE}td:first-child{font-weight:600;background:#F4F7FA;width:45%}footer{margin-top:22px;padding-top:10px;border-top:1px solid #D8E4EE;font-size:10px;color:#64748b}.sign{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:50px}.sign div{border-top:1px solid #64748b;padding-top:5px;text-align:center;font-size:11px}.watermark{position:fixed;inset:40% 0;text-align:center;font-size:60px;opacity:.05;transform:rotate(-25deg);pointer-events:none}</style></head><body>${settings.watermark ? `<div class="watermark">${escapeHtml(settings.watermark)}</div>` : ''}<header><div class="brand">${escapeHtml(profile?.company_name || 'TextileIE')}</div><h1>${escapeHtml(title)}</h1><div class="meta">${escapeHtml(settings.companyAddress || '')}<br>Generated ${new Date().toLocaleString('en-PK')}</div></header><table>${rows}</table><div class="sign"><div>${escapeHtml(settings.preparedBy || 'Prepared By')}</div><div>${escapeHtml(settings.checkedBy || 'Checked By')}</div><div>${escapeHtml(settings.approvedBy || 'Approved By')}</div></div><footer>${escapeHtml(settings.footer || '')}</footer><script>window.onload=()=>window.print()</script></body></html>`);
  win.document.close();
}

function StudioTabs({ active, onChange }) {
  return <div className="card" style={{ padding: 6, display: 'flex', gap: 6, overflowX: 'auto', marginBottom: 18 }}>
    {TABS.map(tab => { const Icon = tab.icon; return <button key={tab.id} className={`btn btn-sm ${active === tab.id ? 'btn-primary' : 'btn-ghost'}`} onClick={() => onChange(tab.id)} style={{ flexShrink: 0 }}><Icon size={14}/>{tab.label}</button>; })}
  </div>;
}

function ReportList({ reports, onOpen, onDelete, onStar, profile, toast }) {
  const [query, setQuery] = useState('');
  const [type, setType] = useState('all');
  const filtered = reports.filter(r => (type === 'all' || r.type === type) && `${r.title} ${getArticle(r)} ${TYPE_LABEL[r.type] || r.type}`.toLowerCase().includes(query.toLowerCase()));
  return <>
    <div style={{ display: 'flex', gap: 8, marginBottom: 14, flexWrap: 'wrap' }}>
      <div style={{ position: 'relative', flex: 1, minWidth: 220 }}><Search size={14} style={{ position:'absolute', left:10, top:'50%', transform:'translateY(-50%)', color:'var(--text-muted)' }}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search report or article..." style={{ paddingLeft: 32 }}/></div>
      <select value={type} onChange={e=>setType(e.target.value)} style={{ width: 190 }}><option value="all">All report types</option>{Object.entries(TYPE_LABEL).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>
    </div>
    {!filtered.length ? <div className="empty-state"><FileText size={32}/><p>No reports match the selected filters.</p></div> : <div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fill,minmax(300px,1fr))', gap:12 }}>
      {filtered.map(r => <div className="card" key={r.id} style={{ padding: 16 }}>
        <div style={{ display:'flex', justifyContent:'space-between', gap:10 }}><div><span className={`badge badge-${TYPE_BADGE[r.type] || 'teal'}`}>{TYPE_LABEL[r.type] || r.type}</span><h3 style={{ marginTop:8 }}>{r.title}</h3><div style={{ fontSize:11,color:'var(--text-muted)',marginTop:4 }}>{getArticle(r) ? `Article ${getArticle(r)} · ` : ''}{new Date(r.created_at).toLocaleDateString('en-PK')}</div></div><button className="btn btn-ghost btn-sm" onClick={()=>onStar(r.id,r.is_starred)}><Star size={15} fill={r.is_starred ? 'var(--amber)' : 'none'} color={r.is_starred ? 'var(--amber)' : 'var(--text-muted)'}/></button></div>
        <div style={{ margin:'14px 0', padding:'10px 12px', background:'var(--teal-light)', borderRadius:8, fontFamily:'JetBrains Mono', color:'var(--teal)', fontWeight:700 }}>{getKeyResult(r)}</div>
        <div style={{ display:'grid', gridTemplateColumns:'1fr 1fr', gap:7 }}><button className="btn btn-primary btn-sm" onClick={()=>onOpen(r)}><Eye size={13}/>Open</button><button className="btn btn-secondary btn-sm" onClick={()=>exportReportPDF({ type:r.type,title:r.title,inputs:r.inputs,results:r.results,companyName:profile?.company_name,userName:profile?.full_name })}><Download size={13}/>PDF</button>{hasBomData(r) && <button className="btn btn-secondary btn-sm" onClick={()=>{ const bom=getBomData(r); bom ? exportBomExcel(bom) : toast('BOM data missing','error'); }}><FileSpreadsheet size={13}/>BOM Excel</button>}<button className="btn btn-danger btn-sm" onClick={()=>onDelete(r.id)}><Trash2 size={13}/>Delete</button></div>
      </div>)}
    </div>}
  </>;
}

function CustomBuilder({ reports, templates, setTemplates, settings, profile, toast, initialReport }) {
  const [reportId, setReportId] = useState(initialReport?.id || '');
  const selected = reports.find(r => String(r.id) === String(reportId)) || initialReport || null;
  const [title, setTitle] = useState(selected?.title || 'Custom TextileIE Report');
  const [fields, setFields] = useState(selected ? createFieldRows(selected) : []);
  const [templateName, setTemplateName] = useState('');
  useEffect(() => { if (selected) { setTitle(selected.title); setFields(createFieldRows(selected)); } }, [reportId, initialReport?.id]);
  const setField = (id, updates) => setFields(prev => prev.map(f => f.id === id ? { ...f, ...updates } : f));
  const move = (index, direction) => setFields(prev => { const next=[...prev]; const target=index+direction; if(target<0||target>=next.length)return prev; [next[index],next[target]]=[next[target],next[index]]; return next; });
  const saveTemplate = () => { if (!selected) return toast('Select a saved report first','error'); if (!templateName.trim()) return toast('Enter a template name','error'); const next=[...templates,{ id:Date.now(), name:templateName.trim(), reportType:selected.type, title, fields:fields.map(({id,source,key,label,visible})=>({id,source,key,label,visible})), createdAt:new Date().toISOString() }]; setTemplates(next); saveJson(REPORT_TEMPLATE_KEY,next); setTemplateName(''); toast('Report template saved'); };
  return <div style={{ display:'grid', gridTemplateColumns:'minmax(320px, 420px) 1fr', gap:18 }} className="report-builder-grid">
    <div style={{ display:'flex', flexDirection:'column', gap:14 }}>
      <div className="card"><h3 style={{marginBottom:14}}>Report source</h3><div className="field"><label>Saved report</label><select value={reportId} onChange={e=>setReportId(e.target.value)}><option value="">Select report</option>{reports.map(r=><option key={r.id} value={r.id}>{TYPE_LABEL[r.type] || r.type} — {r.title}</option>)}</select></div><div className="field"><label>Report title</label><input value={title} onChange={e=>setTitle(e.target.value)}/></div></div>
      {selected && <div className="card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:12}}><h3>Fields</h3><span className="badge badge-teal">{fields.filter(f=>f.visible).length} visible</span></div><div style={{display:'flex',flexDirection:'column',gap:7,maxHeight:430,overflowY:'auto'}}>{fields.map((f,i)=><div key={f.id} style={{padding:9,border:'1px solid var(--border-light)',borderRadius:8,background:f.visible?'white':'var(--bg)'}}><div style={{display:'flex',gap:7,alignItems:'center'}}><input type="checkbox" checked={f.visible} onChange={e=>setField(f.id,{visible:e.target.checked})} style={{width:16}}/><input value={f.label} onChange={e=>setField(f.id,{label:e.target.value})} style={{flex:1,padding:'5px 7px'}}/><button className="btn btn-ghost btn-sm" onClick={()=>move(i,-1)} disabled={i===0}><ChevronUp size={13}/></button><button className="btn btn-ghost btn-sm" onClick={()=>move(i,1)} disabled={i===fields.length-1}><ChevronDown size={13}/></button></div></div>)}</div></div>}
      {selected && <div className="card"><h3 style={{marginBottom:12}}>Save template</h3><div style={{display:'flex',gap:8}}><input value={templateName} onChange={e=>setTemplateName(e.target.value)} placeholder="e.g. Buyer Cost Sheet"/><button className="btn btn-primary" onClick={saveTemplate}><Save size={14}/></button></div></div>}
    </div>
    <div className="card" style={{padding:0,overflow:'hidden',alignSelf:'start',position:'sticky',top:0}}><div style={{padding:'12px 16px',background:'var(--navy)',color:'white',display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontWeight:700}}>Live preview</div><div style={{fontSize:10,opacity:.55}}>{settings.defaultPaper} · {settings.defaultOrientation}</div></div>{selected && <div style={{display:'flex',gap:7}}><button className="btn btn-sm" style={{background:'rgba(255,255,255,.14)',color:'white'}} onClick={()=>printCustomReport({title,fields,settings,profile})}><Download size={13}/>Print / PDF</button><button className="btn btn-sm" style={{background:'#217346',color:'white'}} onClick={()=>downloadExcel({title,fields,settings})}><FileSpreadsheet size={13}/>Excel</button></div>}</div>{!selected ? <div className="empty-state"><Palette size={34}/><p>Select a saved report to begin designing.</p></div> : <div style={{padding:24,minHeight:500,background:'white'}}><div style={{borderBottom:'3px solid var(--teal)',paddingBottom:12,marginBottom:18}}><div style={{fontSize:12,color:'var(--text-muted)'}}>{profile?.company_name || 'TextileIE'}</div><h2 style={{fontSize:22,marginTop:3}}>{title}</h2>{settings.companyAddress && <div style={{fontSize:11,color:'var(--text-muted)',marginTop:4}}>{settings.companyAddress}</div>}</div><div style={{display:'flex',flexDirection:'column',gap:0}}>{fields.filter(f=>f.visible).map(f=><div key={f.id} style={{display:'grid',gridTemplateColumns:'1fr 1fr',borderBottom:'1px solid var(--border-light)'}}><div style={{padding:'9px 10px',fontWeight:600,background:'var(--bg)'}}>{f.label}</div><div style={{padding:'9px 10px',fontFamily:'JetBrains Mono'}}>{f.value}</div></div>)}</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:20,marginTop:48,fontSize:11,textAlign:'center'}}>{[settings.preparedBy||'Prepared By',settings.checkedBy||'Checked By',settings.approvedBy||'Approved By'].map(x=><div key={x} style={{borderTop:'1px solid var(--text-muted)',paddingTop:6}}>{x}</div>)}</div><div style={{marginTop:28,paddingTop:8,borderTop:'1px solid var(--border-light)',fontSize:10,color:'var(--text-muted)'}}>{settings.footer}</div></div>}</div>
  </div>;
}

function SavedTemplates({ templates, setTemplates, reports, settings, profile, toast, onUse }) {
  const remove = id => { const next=templates.filter(t=>t.id!==id); setTemplates(next); saveJson(REPORT_TEMPLATE_KEY,next); toast('Template deleted'); };
  return !templates.length ? <div className="empty-state"><Star size={34}/><p>No custom templates yet. Create one in Custom Builder.</p></div> : <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill,minmax(280px,1fr))',gap:12}}>{templates.map(t=><div className="card" key={t.id}><span className={`badge badge-${TYPE_BADGE[t.reportType] || 'teal'}`}>{TYPE_LABEL[t.reportType] || t.reportType}</span><h3 style={{marginTop:10}}>{t.name}</h3><div style={{fontSize:11,color:'var(--text-muted)',margin:'6px 0 14px'}}>{t.fields.filter(f=>f.visible).length} visible fields · {new Date(t.createdAt).toLocaleDateString('en-PK')}</div><div style={{display:'grid',gridTemplateColumns:'1fr auto',gap:8}}><button className="btn btn-primary btn-sm" onClick={()=>onUse(t)}><Palette size={13}/>Use template</button><button className="btn btn-danger btn-sm" onClick={()=>remove(t.id)}><Trash2 size={13}/></button></div></div>)}</div>;
}

function ExecutiveReports({ reports }) {
  const byType = reports.reduce((a,r)=>{a[r.type]=(a[r.type]||0)+1;return a;},{});
  const latestCosting = reports.find(r=>r.type==='costing');
  const latestEfficiency = reports.find(r=>r.type==='efficiency');
  const articleSet = new Set(reports.map(getArticle).filter(Boolean));
  const cards = [
    ['Saved reports', reports.length, 'var(--teal)'], ['Articles covered', articleSet.size, 'var(--blue)'],
    ['Latest efficiency', latestEfficiency ? `${Number(latestEfficiency.results?.efficiency||0).toFixed(1)}%` : '—', 'var(--amber)'],
    ['Latest FOB', latestCosting ? Number(latestCosting.results?.fobPrice||0).toFixed(2) : '—', 'var(--green)'],
  ];
  return <div><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12,marginBottom:18}}>{cards.map(([l,v,c])=><div className="card" key={l}><div style={{fontSize:26,fontWeight:700,fontFamily:'JetBrains Mono',color:c}}>{v}</div><div style={{fontSize:12,color:'var(--text-muted)',marginTop:4}}>{l}</div></div>)}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16}}><div className="card"><h3 style={{marginBottom:14}}>Reports by module</h3>{Object.entries(TYPE_LABEL).map(([key,label])=><div key={key} style={{display:'flex',justifyContent:'space-between',padding:'8px 0',borderBottom:'1px solid var(--border-light)'}}><span>{label}</span><strong>{byType[key]||0}</strong></div>)}</div><div className="card"><h3 style={{marginBottom:14}}>Recent management activity</h3>{reports.slice(0,8).map(r=><div key={r.id} style={{padding:'8px 0',borderBottom:'1px solid var(--border-light)'}}><div style={{fontSize:13,fontWeight:600}}>{r.title}</div><div style={{fontSize:11,color:'var(--text-muted)',marginTop:2}}>{TYPE_LABEL[r.type]||r.type} · {new Date(r.created_at).toLocaleDateString('en-PK')}</div></div>)}</div></div></div>;
}

export default function ReportsPage() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState('standard');
  const [builderReport, setBuilderReport] = useState(null);
  const [builderTemplate, setBuilderTemplate] = useState(null);
  const [templates, setTemplates] = useState(() => loadJson(REPORT_TEMPLATE_KEY, []));
  const [settings] = useState(() => ({ ...DEFAULT_REPORT_SETTINGS, ...loadJson(REPORT_SETTINGS_KEY, {}) }));
  const { profile } = useAuth();
  const { toast, ToastContainer } = useToast();
  const load = async () => { setLoading(true); try { setReports(await getReports({ limit: 300 })); } catch(e){ toast('Failed to load reports','error'); } finally { setLoading(false); } };
  useEffect(()=>{load();},[]);
  const del = async id => { if(!confirm('Delete this report?'))return; try{await deleteReport(id);setReports(p=>p.filter(r=>r.id!==id));toast('Report deleted');}catch(e){toast('Delete failed','error');} };
  const star = async(id,current)=>{try{const u=await toggleStar(id,current);setReports(p=>p.map(r=>r.id===id?{...r,is_starred:u.is_starred}:r));}catch{toast('Update failed','error');}};
  const openBuilder = report => { setBuilderReport(report); setBuilderTemplate(null); setActiveTab('builder'); };
  const useTemplate = template => { const report=reports.find(r=>r.type===template.reportType) || reports[0]; if(!report)return toast('No compatible saved report exists','error'); setBuilderReport(report); setBuilderTemplate(template); setActiveTab('builder'); };
  return <div><ToastContainer/><PageHeader title="Report Studio" subtitle="Standard reports, custom layouts, reusable templates and executive summaries" badge={{text:'Enterprise Reports'}}/><StudioTabs active={activeTab} onChange={setActiveTab}/>{loading ? <div className="empty-state"><p>Loading Report Studio...</p></div> : activeTab==='standard' ? <ReportList reports={reports} onOpen={openBuilder} onDelete={del} onStar={star} profile={profile} toast={toast}/> : activeTab==='builder' ? <CustomBuilder key={`${builderReport?.id||'none'}-${builderTemplate?.id||'none'}`} reports={reports} templates={templates} setTemplates={setTemplates} settings={settings} profile={profile} toast={toast} initialReport={builderReport}/> : activeTab==='templates' ? <SavedTemplates templates={templates} setTemplates={setTemplates} reports={reports} settings={settings} profile={profile} toast={toast} onUse={useTemplate}/> : <ExecutiveReports reports={reports}/>}<style>{`@media(max-width:900px){.report-builder-grid{grid-template-columns:1fr!important}.report-builder-grid>div:last-child{position:static!important}}`}</style></div>;
                             }
