import { useMemo, useState } from 'react';
import {
  Bell,
  Building2,
  Check,
  CreditCard,
  Factory,
  FileText,
  Layers3,
  Lock,
  MapPin,
  Plus,
  Save,
  Settings2,
  ShieldCheck,
  Trash2,
  User,
  Users,
  Workflow,
} from 'lucide-react';
import { useAuth } from '../hooks/useAuth.jsx';
import UserManagement from '../components/UserManagement.jsx';
import PermissionMatrix from '../components/PermissionMatrix.jsx';
import { updateProfile } from '../lib/db.js';
import { supabase } from '../lib/supabase.js';
import { useToast } from '../hooks/useToast.jsx';
import { PageHeader } from '../components/ResultCard.jsx';

const STORAGE_KEY = 'textileie_administration_v1';
const REPORT_SETTINGS_KEY = 'textileie_report_settings_v1';

const DEFAULT_ADMIN = {
  company: {
    legalName: '',
    tradingName: '',
    companyCode: '',
    address: '',
    city: '',
    country: 'Pakistan',
    phone: '',
    email: '',
    website: '',
    currency: 'USD',
    timezone: 'Asia/Karachi',
    fiscalYearStart: 'July',
  },
  factory: {
    factoryName: '',
    factoryCode: '',
    city: '',
    country: 'Pakistan',
    workingDays: 26,
    workingHours: 8,
    shifts: 1,
    sewingLines: 1,
  },
  departments: [
    { id: 'cutting', name: 'Cutting', code: 'CUT', status: 'Active' },
    { id: 'sewing', name: 'Sewing', code: 'SEW', status: 'Active' },
    { id: 'finishing', name: 'Finishing', code: 'FIN', status: 'Active' },
    { id: 'packing', name: 'Packing', code: 'PAC', status: 'Active' },
    { id: 'quality', name: 'Quality', code: 'QUA', status: 'Active' },
    { id: 'warehouse', name: 'Warehouse', code: 'WHS', status: 'Active' },
    { id: 'merchandising', name: 'Merchandising', code: 'MER', status: 'Active' },
    { id: 'ie', name: 'Industrial Engineering', code: 'IE', status: 'Active' },
  ],
  lines: [
    { id: 'line-1', name: 'Line 01', code: 'L01', department: 'Sewing', status: 'Active' },
  ],
  modules: {
    dashboard: true,
    styleMaster: true,
    fabricMaster: true,
    threadMaster: true,
    stitchMaster: true,
    smv: true,
    efficiency: true,
    capacity: true,
    fabricEngineering: true,
    threadEngineering: true,
    costing: true,
    reports: true,
    inventory: false,
    ai: false,
    ghl: false,
  },
  notifications: {
    duplicateRecords: true,
    styleIncomplete: true,
    costingCompleted: true,
    efficiencyBelowTarget: true,
    capacityOverload: true,
    lowStock: false,
    reportReady: true,
    userApproval: true,
  },
  costing: {
    defaultCurrency: 'USD',
    cmtRatePerMinute: 0.05,
    defaultProfitPct: 20,
    defaultOverheadPerUnit: 0,
    defaultFreightPerUnit: 0,
  },
};

const DEFAULT_REPORT_SETTINGS = {
  companyLogo: '',
  companyAddress: '',
  defaultPaper: 'A4',
  defaultOrientation: 'portrait',
  footer: 'Generated by TextileIE',
  watermark: '',
  preparedBy: 'Prepared By',
  checkedBy: 'Checked By',
  approvedBy: 'Approved By',
  showPageNumber: true,
  showGeneratedBy: true,
};

const TABS = [
  { id: 'company', label: 'Company', icon: Building2 },
  { id: 'factory', label: 'Factory', icon: Factory },
  { id: 'departments', label: 'Departments', icon: Layers3 },
  { id: 'lines', label: 'Production Lines', icon: Workflow },
  { id: 'users', label: 'Users', icon: Users },
  { id: 'permissions', label: 'Roles & Permissions', icon: ShieldCheck },
  { id: 'modules', label: 'Modules', icon: Settings2 },
  { id: 'notifications', label: 'Notifications', icon: Bell },
  { id: 'reports', label: 'Report Settings', icon: FileText },
  { id: 'costing', label: 'Costing Defaults', icon: CreditCard },
  { id: 'security', label: 'Security', icon: Lock },
  { id: 'subscription', label: 'Subscription', icon: CreditCard },
];

const MODULE_LABELS = {
  dashboard: 'Dashboard',
  styleMaster: 'Style Master',
  fabricMaster: 'Fabric Master',
  threadMaster: 'Thread Master',
  stitchMaster: 'Stitch Master',
  smv: 'SMV / SAM',
  efficiency: 'Efficiency',
  capacity: 'Capacity Planning',
  fabricEngineering: 'Fabric Engineering',
  threadEngineering: 'Thread Engineering',
  costing: 'Garment Costing',
  reports: 'Report Studio',
  inventory: 'Inventory',
  ai: 'AI Advisor',
  ghl: 'GHL Automation',
};

const NOTIFICATION_LABELS = {
  duplicateRecords: 'Duplicate record detected',
  styleIncomplete: 'Style engineering is incomplete',
  costingCompleted: 'Garment costing completed',
  efficiencyBelowTarget: 'Efficiency below target',
  capacityOverload: 'Capacity exceeds available resources',
  lowStock: 'Inventory stock below reorder level',
  reportReady: 'Report is ready',
  userApproval: 'User or master record awaiting approval',
};

function safeLoad(key, fallback) {
  try {
    return { ...fallback, ...(JSON.parse(localStorage.getItem(key) || '{}')) };
  } catch {
    return fallback;
  }
}

function SectionTitle({ icon: Icon, title, subtitle }) {
  return (
    <div style={{ display: 'flex', alignItems: 'flex-start', gap: 10, marginBottom: 18 }}>
      <div style={{
        width: 36, height: 36, borderRadius: 10, background: 'var(--teal-light)',
        display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
      }}>
        <Icon size={17} color="var(--teal)" />
      </div>
      <div>
        <h2 style={{ fontSize: 17 }}>{title}</h2>
        {subtitle && <p style={{ fontSize: 12, color: 'var(--text-muted)', marginTop: 2 }}>{subtitle}</p>}
      </div>
    </div>
  );
}

function Toggle({ checked, onChange, label, disabled = false }) {
  return (
    <label style={{
      display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      gap: 14, padding: '12px 14px', border: '1px solid var(--border-light)',
      borderRadius: 10, background: disabled ? 'var(--bg)' : 'white',
      cursor: disabled ? 'not-allowed' : 'pointer', margin: 0,
    }}>
      <span style={{ fontSize: 13, fontWeight: 500, color: disabled ? 'var(--text-muted)' : 'var(--text-primary)' }}>{label}</span>
      <input type="checkbox" checked={checked} onChange={onChange} disabled={disabled} style={{ width: 18, height: 18 }} />
    </label>
  );
}

function StatusPill({ children, tone = 'green' }) {
  const map = {
    green: ['var(--green-light)', 'var(--green)'],
    amber: ['var(--amber-light)', 'var(--amber)'],
    navy: ['#E8EEF5', 'var(--navy)'],
  };
  return (
    <span style={{
      background: map[tone][0], color: map[tone][1], padding: '3px 8px',
      borderRadius: 20, fontSize: 11, fontWeight: 700,
    }}>{children}</span>
  );
}

export default function SettingsPage() {
  const { user, profile, refreshProfile } = useAuth();
  const { toast, ToastContainer } = useToast();

  const [activeTab, setActiveTab] = useState('company');
  const [admin, setAdmin] = useState(() => {
    const saved = safeLoad(STORAGE_KEY, DEFAULT_ADMIN);
    return {
      ...DEFAULT_ADMIN,
      ...saved,
      company: { ...DEFAULT_ADMIN.company, ...(saved.company || {}) },
      factory: { ...DEFAULT_ADMIN.factory, ...(saved.factory || {}) },
      modules: { ...DEFAULT_ADMIN.modules, ...(saved.modules || {}) },
      notifications: { ...DEFAULT_ADMIN.notifications, ...(saved.notifications || {}) },
      costing: { ...DEFAULT_ADMIN.costing, ...(saved.costing || {}) },
      departments: saved.departments || DEFAULT_ADMIN.departments,
      lines: saved.lines || DEFAULT_ADMIN.lines,
    };
  });
  const [reportSettings, setReportSettings] = useState(() => safeLoad(REPORT_SETTINGS_KEY, DEFAULT_REPORT_SETTINGS));
  const [profileForm, setProfileForm] = useState({
    full_name: profile?.full_name || '',
    company_name: profile?.company_name || '',
  });
  const [pwForm, setPwForm] = useState({ newPw: '', confirm: '' });
  const [savingProfile, setSavingProfile] = useState(false);
  const [savingPw, setSavingPw] = useState(false);
  const [newDepartment, setNewDepartment] = useState({ name: '', code: '' });
  const [newLine, setNewLine] = useState({ name: '', code: '', department: 'Sewing' });

  const saveAdmin = (message = 'Administration settings saved') => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(admin));
    toast(message);
  };

  const companyDisplayName = admin.company.tradingName || admin.company.legalName || profileForm.company_name || 'TextileIE Factory';

  const activeModuleCount = useMemo(
    () => Object.values(admin.modules).filter(Boolean).length,
    [admin.modules]
  );

  const setCompany = (key, value) => setAdmin(prev => ({ ...prev, company: { ...prev.company, [key]: value } }));
  const setFactory = (key, value) => setAdmin(prev => ({ ...prev, factory: { ...prev.factory, [key]: value } }));
  const setCosting = (key, value) => setAdmin(prev => ({ ...prev, costing: { ...prev.costing, [key]: value } }));
  const setReport = (key, value) => setReportSettings(prev => ({ ...prev, [key]: value }));

  const saveCompany = async () => {
    if (!profileForm.full_name.trim() || !companyDisplayName.trim()) {
      toast('Full name and company name are required', 'error');
      return;
    }
    setSavingProfile(true);
    try {
      const companyName = companyDisplayName.trim();
      await updateProfile(user.id, { full_name: profileForm.full_name.trim(), company_name: companyName });
      setProfileForm(prev => ({ ...prev, company_name: companyName }));
      await refreshProfile();
      localStorage.setItem(STORAGE_KEY, JSON.stringify(admin));
      toast('Company and profile saved');
    } catch (error) {
      toast(error.message || 'Failed to save company', 'error');
    } finally {
      setSavingProfile(false);
    }
  };

  const saveReports = () => {
    localStorage.setItem(REPORT_SETTINGS_KEY, JSON.stringify(reportSettings));
    toast('Report settings saved');
  };

  const changePassword = async () => {
    if (pwForm.newPw.length < 6) {
      toast('Password must be at least 6 characters', 'error');
      return;
    }
    if (pwForm.newPw !== pwForm.confirm) {
      toast('Passwords do not match', 'error');
      return;
    }
    setSavingPw(true);
    try {
      const { error } = await supabase.auth.updateUser({ password: pwForm.newPw });
      if (error) throw error;
      setPwForm({ newPw: '', confirm: '' });
      toast('Password changed');
    } catch (error) {
      toast(error.message || 'Failed to change password', 'error');
    } finally {
      setSavingPw(false);
    }
  };

  const addDepartment = () => {
    const name = newDepartment.name.trim();
    const code = newDepartment.code.trim().toUpperCase();
    if (!name || !code) return toast('Department name and code are required', 'error');
    const duplicate = admin.departments.some(d =>
      d.name.trim().toLowerCase() === name.toLowerCase() || d.code.trim().toUpperCase() === code
    );
    if (duplicate) return toast('Department name or code already exists', 'error');
    setAdmin(prev => ({
      ...prev,
      departments: [...prev.departments, { id: crypto.randomUUID(), name, code, status: 'Active' }],
    }));
    setNewDepartment({ name: '', code: '' });
  };

  const addLine = () => {
    const name = newLine.name.trim();
    const code = newLine.code.trim().toUpperCase();
    if (!name || !code) return toast('Line name and code are required', 'error');
    const duplicate = admin.lines.some(l =>
      l.name.trim().toLowerCase() === name.toLowerCase() || l.code.trim().toUpperCase() === code
    );
    if (duplicate) return toast('Production line name or code already exists', 'error');
    setAdmin(prev => ({
      ...prev,
      lines: [...prev.lines, { id: crypto.randomUUID(), name, code, department: newLine.department, status: 'Active' }],
    }));
    setNewLine({ name: '', code: '', department: 'Sewing' });
  };

  return (
    <div>
      <ToastContainer />
      <PageHeader
        title="Administration"
        subtitle="Configure company, factory, modules, notifications and enterprise controls"
        badge={{ text: 'Enterprise' }}
      />

      <div style={{
        display: 'grid', gridTemplateColumns: '240px minmax(0, 1fr)', gap: 18,
        alignItems: 'start',
      }} className="administration-layout">
        <aside className="card administration-tabs" style={{ padding: 8, position: 'sticky', top: 0 }}>
          <div style={{ padding: '10px 12px 12px', borderBottom: '1px solid var(--border-light)', marginBottom: 6 }}>
            <div style={{ fontWeight: 700, fontSize: 13 }}>{companyDisplayName}</div>
            <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>
              {activeModuleCount} active modules
            </div>
          </div>
          {TABS.map(tab => {
            const Icon = tab.icon;
            return (
              <button key={tab.id} type="button" onClick={() => setActiveTab(tab.id)} style={{
                width: '100%', display: 'flex', alignItems: 'center', gap: 9,
                padding: '9px 10px', border: 'none', borderRadius: 8, cursor: 'pointer',
                fontFamily: 'inherit', fontSize: 12, textAlign: 'left',
                background: activeTab === tab.id ? 'var(--teal-light)' : 'transparent',
                color: activeTab === tab.id ? 'var(--teal)' : 'var(--text-secondary)',
                fontWeight: activeTab === tab.id ? 700 : 500,
              }}>
                <Icon size={14} /> {tab.label}
              </button>
            );
          })}
        </aside>

        <div>
          {activeTab === 'company' && (
            <div className="card">
              <SectionTitle icon={Building2} title="Company Profile" subtitle="Legal identity and primary business information" />
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(220px,1fr))', gap: 12 }}>
                <div className="field"><label>Full name *</label><input value={profileForm.full_name} onChange={e => setProfileForm(p => ({ ...p, full_name: e.target.value }))} /></div>
                <div className="field"><label>Legal company name *</label><input value={admin.company.legalName} onChange={e => setCompany('legalName', e.target.value)} placeholder={profile?.company_name || 'Silver Star Pvt Ltd'} /></div>
                <div className="field"><label>Trading name</label><input value={admin.company.tradingName} onChange={e => setCompany('tradingName', e.target.value)} placeholder="TextileIE Demo Factory" /></div>
                <div className="field"><label>Company code</label><input value={admin.company.companyCode} onChange={e => setCompany('companyCode', e.target.value.toUpperCase())} placeholder="SSPL" /></div>
                <div className="field"><label>Email</label><input value={admin.company.email} onChange={e => setCompany('email', e.target.value)} placeholder="info@factory.com" /></div>
                <div className="field"><label>Phone</label><input value={admin.company.phone} onChange={e => setCompany('phone', e.target.value)} /></div>
                <div className="field"><label>Website</label><input value={admin.company.website} onChange={e => setCompany('website', e.target.value)} placeholder="www.factory.com" /></div>
                <div className="field"><label>Currency</label><select value={admin.company.currency} onChange={e => setCompany('currency', e.target.value)}><option>USD</option><option>PKR</option><option>EUR</option><option>GBP</option><option>CNY</option></select></div>
                <div className="field"><label>Time zone</label><select value={admin.company.timezone} onChange={e => setCompany('timezone', e.target.value)}><option value="Asia/Karachi">Asia/Karachi</option><option value="Asia/Dhaka">Asia/Dhaka</option><option value="Asia/Colombo">Asia/Colombo</option><option value="Europe/Rome">Europe/Rome</option></select></div>
                <div className="field"><label>Fiscal year starts</label><select value={admin.company.fiscalYearStart} onChange={e => setCompany('fiscalYearStart', e.target.value)}>{['January','April','July','October'].map(x => <option key={x}>{x}</option>)}</select></div>
                <div className="field"><label>City</label><input value={admin.company.city} onChange={e => setCompany('city', e.target.value)} /></div>
                <div className="field"><label>Country</label><input value={admin.company.country} onChange={e => setCompany('country', e.target.value)} /></div>
                <div className="field" style={{ gridColumn: '1 / -1' }}><label>Address</label><textarea rows={3} value={admin.company.address} onChange={e => setCompany('address', e.target.value)} /></div>
              </div>
              <button className="btn btn-primary" onClick={saveCompany} disabled={savingProfile}><Save size={14} />{savingProfile ? 'Saving...' : 'Save Company'}</button>
            </div>
          )}

          {activeTab === 'factory' && (
            <div className="card">
              <SectionTitle icon={Factory} title="Factory Configuration" subtitle="Operational defaults used by planning, efficiency and capacity" />
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(220px,1fr))', gap: 12 }}>
                <div className="field"><label>Factory name *</label><input value={admin.factory.factoryName} onChange={e => setFactory('factoryName', e.target.value)} /></div>
                <div className="field"><label>Factory code *</label><input value={admin.factory.factoryCode} onChange={e => setFactory('factoryCode', e.target.value.toUpperCase())} /></div>
                <div className="field"><label>City</label><input value={admin.factory.city} onChange={e => setFactory('city', e.target.value)} /></div>
                <div className="field"><label>Country</label><input value={admin.factory.country} onChange={e => setFactory('country', e.target.value)} /></div>
                <div className="field"><label>Working days / month</label><input type="number" min="1" value={admin.factory.workingDays} onChange={e => setFactory('workingDays', Number(e.target.value || 0))} /></div>
                <div className="field"><label>Working hours / shift</label><input type="number" min="1" step="0.5" value={admin.factory.workingHours} onChange={e => setFactory('workingHours', Number(e.target.value || 0))} /></div>
                <div className="field"><label>Shifts / day</label><input type="number" min="1" value={admin.factory.shifts} onChange={e => setFactory('shifts', Number(e.target.value || 0))} /></div>
                <div className="field"><label>Sewing lines</label><input type="number" min="0" value={admin.factory.sewingLines} onChange={e => setFactory('sewingLines', Number(e.target.value || 0))} /></div>
              </div>
              <button className="btn btn-primary" onClick={() => saveAdmin('Factory settings saved')}><Save size={14} />Save Factory</button>
            </div>
          )}

          {activeTab === 'departments' && (
            <div className="card">
              <SectionTitle icon={Layers3} title="Departments" subtitle="Add factory departments and keep codes unique" />
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 140px auto', gap: 8, marginBottom: 16 }}>
                <input value={newDepartment.name} onChange={e => setNewDepartment(p => ({ ...p, name: e.target.value }))} placeholder="Department name" />
                <input value={newDepartment.code} onChange={e => setNewDepartment(p => ({ ...p, code: e.target.value.toUpperCase() }))} placeholder="Code" />
                <button className="btn btn-primary" onClick={addDepartment}><Plus size={14} />Add</button>
              </div>
              <div className="data-table-wrap">
                <table className="data-table">
                  <thead><tr><th>Department</th><th>Code</th><th>Status</th><th style={{ width: 80 }}>Action</th></tr></thead>
                  <tbody>
                    {admin.departments.map(dept => (
                      <tr key={dept.id}>
                        <td>{dept.name}</td><td><strong>{dept.code}</strong></td><td><StatusPill>{dept.status}</StatusPill></td>
                        <td><button className="btn btn-danger btn-sm" onClick={() => setAdmin(p => ({ ...p, departments: p.departments.filter(x => x.id !== dept.id) }))}><Trash2 size={12} /></button></td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <button className="btn btn-primary" style={{ marginTop: 14 }} onClick={() => saveAdmin('Departments saved')}><Save size={14} />Save Departments</button>
            </div>
          )}

          {activeTab === 'lines' && (
            <div className="card">
              <SectionTitle icon={Workflow} title="Production Lines" subtitle="Create line master for line-wise efficiency, capacity and reporting" />
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 110px 160px auto', gap: 8, marginBottom: 16 }}>
                <input value={newLine.name} onChange={e => setNewLine(p => ({ ...p, name: e.target.value }))} placeholder="Line name" />
                <input value={newLine.code} onChange={e => setNewLine(p => ({ ...p, code: e.target.value.toUpperCase() }))} placeholder="Code" />
                <select value={newLine.department} onChange={e => setNewLine(p => ({ ...p, department: e.target.value }))}>{admin.departments.map(d => <option key={d.id}>{d.name}</option>)}</select>
                <button className="btn btn-primary" onClick={addLine}><Plus size={14} />Add</button>
              </div>
              <div className="data-table-wrap">
                <table className="data-table">
                  <thead><tr><th>Line</th><th>Code</th><th>Department</th><th>Status</th><th style={{ width: 80 }}>Action</th></tr></thead>
                  <tbody>
                    {admin.lines.map(line => (
                      <tr key={line.id}>
                        <td>{line.name}</td><td><strong>{line.code}</strong></td><td>{line.department}</td><td><StatusPill>{line.status}</StatusPill></td>
                        <td><button className="btn btn-danger btn-sm" onClick={() => setAdmin(p => ({ ...p, lines: p.lines.filter(x => x.id !== line.id) }))}><Trash2 size={12} /></button></td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <button className="btn btn-primary" style={{ marginTop: 14 }} onClick={() => saveAdmin('Production lines saved')}><Save size={14} />Save Lines</button>
            </div>
          )}

          {activeTab === 'users' && (
            <div className="card">
              <UserManagement />
            </div>
          )}

          {activeTab === 'permissions' && (
            <div className="card">
              <PermissionMatrix />
            </div>
          )}

          {activeTab === 'modules' && (
            <div className="card">
              <SectionTitle icon={Settings2} title="Module Management" subtitle="Enable purchased tools for modular enterprise licensing" />
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(230px,1fr))', gap: 10 }}>
                {Object.entries(MODULE_LABELS).map(([key, label]) => {
                  const future = ['inventory', 'ai', 'ghl'].includes(key);
                  return <Toggle key={key} label={future ? `${label} (Future Add-on)` : label} checked={Boolean(admin.modules[key])}
                    onChange={e => setAdmin(p => ({ ...p, modules: { ...p.modules, [key]: e.target.checked } }))} />;
                })}
              </div>
              <button className="btn btn-primary" style={{ marginTop: 16 }} onClick={() => saveAdmin('Module settings saved')}><Save size={14} />Save Modules</button>
            </div>
          )}

          {activeTab === 'notifications' && (
            <div className="card">
              <SectionTitle icon={Bell} title="Notification Rules" subtitle="Choose which alerts appear in the future Notification Center" />
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(260px,1fr))', gap: 10 }}>
                {Object.entries(NOTIFICATION_LABELS).map(([key, label]) => (
                  <Toggle key={key} label={label} checked={Boolean(admin.notifications[key])}
                    onChange={e => setAdmin(p => ({ ...p, notifications: { ...p.notifications, [key]: e.target.checked } }))} />
                ))}
              </div>
              <button className="btn btn-primary" style={{ marginTop: 16 }} onClick={() => saveAdmin('Notification settings saved')}><Save size={14} />Save Notifications</button>
            </div>
          )}

          {activeTab === 'reports' && (
            <div className="card">
              <SectionTitle icon={FileText} title="Report Branding & Defaults" subtitle="Applied to Report Studio templates and exports" />
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(220px,1fr))', gap: 12 }}>
                <div className="field"><label>Company address</label><input value={reportSettings.companyAddress} onChange={e => setReport('companyAddress', e.target.value)} /></div>
                <div className="field"><label>Default paper</label><select value={reportSettings.defaultPaper} onChange={e => setReport('defaultPaper', e.target.value)}><option>A4</option><option>Letter</option><option>Legal</option></select></div>
                <div className="field"><label>Orientation</label><select value={reportSettings.defaultOrientation} onChange={e => setReport('defaultOrientation', e.target.value)}><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></div>
                <div className="field"><label>Watermark</label><input value={reportSettings.watermark} onChange={e => setReport('watermark', e.target.value)} placeholder="CONFIDENTIAL" /></div>
                <div className="field"><label>Prepared by label</label><input value={reportSettings.preparedBy} onChange={e => setReport('preparedBy', e.target.value)} /></div>
                <div className="field"><label>Checked by label</label><input value={reportSettings.checkedBy} onChange={e => setReport('checkedBy', e.target.value)} /></div>
                <div className="field"><label>Approved by label</label><input value={reportSettings.approvedBy} onChange={e => setReport('approvedBy', e.target.value)} /></div>
                <div className="field" style={{ gridColumn: '1 / -1' }}><label>Footer</label><input value={reportSettings.footer} onChange={e => setReport('footer', e.target.value)} /></div>
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(230px,1fr))', gap: 10, marginBottom: 16 }}>
                <Toggle label="Show page numbers" checked={reportSettings.showPageNumber} onChange={e => setReport('showPageNumber', e.target.checked)} />
                <Toggle label="Show generated-by details" checked={reportSettings.showGeneratedBy} onChange={e => setReport('showGeneratedBy', e.target.checked)} />
              </div>
              <button className="btn btn-primary" onClick={saveReports}><Save size={14} />Save Report Settings</button>
            </div>
          )}

          {activeTab === 'costing' && (
            <div className="card">
              <SectionTitle icon={CreditCard} title="Costing Defaults" subtitle="Defaults used when a new garment costing is created" />
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(220px,1fr))', gap: 12 }}>
                <div className="field"><label>Default currency</label><select value={admin.costing.defaultCurrency} onChange={e => setCosting('defaultCurrency', e.target.value)}><option>USD</option><option>PKR</option><option>EUR</option><option>GBP</option></select></div>
                <div className="field"><label>CMT rate / minute</label><input type="number" step="0.001" value={admin.costing.cmtRatePerMinute} onChange={e => setCosting('cmtRatePerMinute', Number(e.target.value || 0))} /></div>
                <div className="field"><label>Default profit %</label><input type="number" step="0.1" value={admin.costing.defaultProfitPct} onChange={e => setCosting('defaultProfitPct', Number(e.target.value || 0))} /></div>
                <div className="field"><label>Overhead / unit</label><input type="number" step="0.01" value={admin.costing.defaultOverheadPerUnit} onChange={e => setCosting('defaultOverheadPerUnit', Number(e.target.value || 0))} /></div>
                <div className="field"><label>Freight / unit</label><input type="number" step="0.01" value={admin.costing.defaultFreightPerUnit} onChange={e => setCosting('defaultFreightPerUnit', Number(e.target.value || 0))} /></div>
              </div>
              <button className="btn btn-primary" onClick={() => saveAdmin('Costing defaults saved')}><Save size={14} />Save Costing Defaults</button>
            </div>
          )}

          {activeTab === 'security' && (
            <div className="card">
              <SectionTitle icon={Lock} title="Security" subtitle="Manage your account password" />
              <div style={{ maxWidth: 480 }}>
                <div className="field"><label>Email</label><input value={user?.email || ''} disabled /></div>
                <div className="field"><label>New password</label><input type="password" value={pwForm.newPw} onChange={e => setPwForm(p => ({ ...p, newPw: e.target.value }))} /></div>
                <div className="field"><label>Confirm password</label><input type="password" value={pwForm.confirm} onChange={e => setPwForm(p => ({ ...p, confirm: e.target.value }))} /></div>
                <button className="btn btn-primary" onClick={changePassword} disabled={savingPw}><Lock size={14} />{savingPw ? 'Changing...' : 'Change Password'}</button>
              </div>
            </div>
          )}

          {activeTab === 'subscription' && (
            <div className="card">
              <SectionTitle icon={CreditCard} title="Subscription" subtitle="30-day trial and modular enterprise licensing" />
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(220px,1fr))', gap: 12 }}>
                <div style={{ padding: 16, border: '1px solid var(--border-light)', borderRadius: 12 }}>
                  <div style={{ fontSize: 11, color: 'var(--text-muted)', textTransform: 'uppercase' }}>Current Plan</div>
                  <div style={{ fontSize: 20, fontWeight: 800, marginTop: 5 }}>Free Trial</div>
                  <div style={{ fontSize: 12, color: 'var(--text-muted)', marginTop: 5 }}>Subscription billing will be connected before public launch.</div>
                </div>
                <div style={{ padding: 16, border: '1px solid var(--border-light)', borderRadius: 12 }}>
                  <div style={{ fontSize: 11, color: 'var(--text-muted)', textTransform: 'uppercase' }}>Licensing Model</div>
                  <div style={{ fontSize: 20, fontWeight: 800, marginTop: 5 }}>Modular</div>
                  <div style={{ fontSize: 12, color: 'var(--text-muted)', marginTop: 5 }}>Factories can purchase only the tools they need.</div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      <style>{`
        @media (max-width: 900px) {
          .administration-layout { grid-template-columns: 1fr !important; }
          .administration-tabs {
            position: static !important;
            display: flex !important;
            overflow-x: auto !important;
            gap: 4px !important;
          }
          .administration-tabs > div { display: none !important; }
          .administration-tabs button { width: auto !important; flex-shrink: 0 !important; white-space: nowrap !important; }
        }
        @media (max-width: 640px) {
          .administration-layout .data-table { min-width: 580px; }
        }
      `}</style>
    </div>
  );
}
