import { useState } from 'react';
import { useAuth } from '../hooks/useAuth.jsx';
import { updateProfile } from '../lib/db.js';
import { supabase } from '../lib/supabase.js';
import { useToast } from '../hooks/useToast.jsx';
import { PageHeader } from '../components/ResultCard.jsx';
import { Building2, FileText, Info, Lock, Save, User } from 'lucide-react';

const REPORT_SETTINGS_KEY = 'textileie_report_settings_v1';
const DEFAULT_REPORT_SETTINGS = {
  companyLogo: '', companyAddress: '', defaultPaper: 'A4', defaultOrientation: 'portrait',
  footer: 'Generated by TextileIE', watermark: '', preparedBy: '', checkedBy: '', approvedBy: '',
  showPageNumber: true, showGeneratedBy: true,
};
function loadSettings() { try { return { ...DEFAULT_REPORT_SETTINGS, ...(JSON.parse(localStorage.getItem(REPORT_SETTINGS_KEY) || '{}')) }; } catch { return DEFAULT_REPORT_SETTINGS; } }

export default function SettingsPage() {
  const { user, profile, refreshProfile } = useAuth();
  const { toast, ToastContainer } = useToast();
  const [profileForm, setProfileForm] = useState({ full_name: profile?.full_name || '', company_name: profile?.company_name || '' });
  const [reportSettings, setReportSettings] = useState(loadSettings);
  const [pwForm, setPwForm] = useState({ newPw:'', confirm:'' });
  const [savingProfile,setSavingProfile]=useState(false); const [savingPw,setSavingPw]=useState(false);
  const setP = k => e => setProfileForm(f=>({...f,[k]:e.target.value}));
  const setR = k => e => setReportSettings(f=>({...f,[k]:e.target.type==='checkbox'?e.target.checked:e.target.value}));
  const saveProfile = async e => {e.preventDefault(); if(!profileForm.full_name.trim()||!profileForm.company_name.trim())return toast('Name and company are required','error'); setSavingProfile(true);try{await updateProfile(user.id,profileForm);await refreshProfile();toast('Profile updated');}catch(err){toast(err.message||'Failed','error');}finally{setSavingProfile(false);}};
  const saveReports = () => { localStorage.setItem(REPORT_SETTINGS_KEY,JSON.stringify(reportSettings)); toast('Report settings saved'); };
  const changePassword = async e => {e.preventDefault();if(pwForm.newPw.length<6)return toast('Password must be at least 6 characters','error');if(pwForm.newPw!==pwForm.confirm)return toast('Passwords do not match','error');setSavingPw(true);try{const{error}=await supabase.auth.updateUser({password:pwForm.newPw});if(error)throw error;toast('Password changed');setPwForm({newPw:'',confirm:''});}catch(err){toast(err.message||'Failed','error');}finally{setSavingPw(false);}};
  return <div><ToastContainer/><PageHeader title="Administration Settings" subtitle="Profile, company, security and professional report branding" badge={{text:'Administration'}}/><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(340px,1fr))',gap:18,maxWidth:1100}}>
    <div className="card"><div style={{display:'flex',gap:8,alignItems:'center',marginBottom:18}}><User size={17} color="var(--teal)"/><h3>Profile & company</h3></div><form onSubmit={saveProfile}><div className="field"><label>Full name</label><input value={profileForm.full_name} onChange={setP('full_name')}/></div><div className="field"><label>Company / factory name</label><input value={profileForm.company_name} onChange={setP('company_name')}/></div><div className="field"><label>Email</label><input value={user?.email||''} disabled/></div><button className="btn btn-primary btn-full" disabled={savingProfile}><Save size={14}/>{savingProfile?'Saving...':'Save profile'}</button></form></div>
    <div className="card"><div style={{display:'flex',gap:8,alignItems:'center',marginBottom:18}}><Lock size={17} color="var(--amber)"/><h3>Security</h3></div><form onSubmit={changePassword}><div className="field"><label>New password</label><input type="password" value={pwForm.newPw} onChange={e=>setPwForm(f=>({...f,newPw:e.target.value}))}/></div><div className="field"><label>Confirm password</label><input type="password" value={pwForm.confirm} onChange={e=>setPwForm(f=>({...f,confirm:e.target.value}))}/></div><button className="btn btn-primary btn-full" disabled={savingPw}>{savingPw?'Changing...':'Change password'}</button></form></div>
    <div className="card" style={{gridColumn:'1 / -1'}}><div style={{display:'flex',gap:8,alignItems:'center',marginBottom:18}}><FileText size={17} color="var(--blue)"/><h3>Report branding & defaults</h3></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:12}}><div className="field"><label>Company address</label><input value={reportSettings.companyAddress} onChange={setR('companyAddress')} placeholder="Factory address"/></div><div className="field"><label>Default paper</label><select value={reportSettings.defaultPaper} onChange={setR('defaultPaper')}><option>A4</option><option>Letter</option><option>Legal</option></select></div><div className="field"><label>Default orientation</label><select value={reportSettings.defaultOrientation} onChange={setR('defaultOrientation')}><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></div><div className="field"><label>Watermark</label><input value={reportSettings.watermark} onChange={setR('watermark')} placeholder="CONFIDENTIAL"/></div><div className="field"><label>Prepared by label</label><input value={reportSettings.preparedBy} onChange={setR('preparedBy')} placeholder="Prepared By"/></div><div className="field"><label>Checked by label</label><input value={reportSettings.checkedBy} onChange={setR('checkedBy')} placeholder="Checked By"/></div><div className="field"><label>Approved by label</label><input value={reportSettings.approvedBy} onChange={setR('approvedBy')} placeholder="Approved By"/></div><div className="field" style={{gridColumn:'span 2'}}><label>Report footer</label><input value={reportSettings.footer} onChange={setR('footer')} placeholder="Generated by TextileIE"/></div></div><button className="btn btn-primary" onClick={saveReports}><Save size={14}/>Save report settings</button></div>
    <div className="card"><div style={{display:'flex',gap:8,alignItems:'center',marginBottom:14}}><Info size={17} color="var(--green)"/><h3>Application</h3></div>{[['Product','TextileIE'],['Workspace','Industrial Engineering Intelligence'],['Reports','Report Studio v1'],['Backend','Supabase'],['Hosting','Vercel']].map(([k,v])=><div key={k} style={{display:'flex',justifyContent:'space-between',padding:'8px 0',borderBottom:'1px solid var(--border-light)',fontSize:13}}><span style={{color:'var(--text-secondary)'}}>{k}</span><strong>{v}</strong></div>)}</div>
  </div></div>;
}
